### ISSUE TITLE
Incorrect return value

### ISSUE THREAD

**Issue by vHeemstra** [rowanwins/point-in-polygon-hao#10]
Using your package I stumbled upon an incorrect return value from the function.

Example:
```
var point = [-13.571067811865474, 0.5710678118654782];
var shape = [
    [-7.485569452227567, 0.5492713664931865],
    [-19.849242404917497, 9.849242404917499],
    [-16.369523519217765, 3.8036530144735643]
];
var shape_in_reversed_order = [
    [-16.369523519217765, 3.8036530144735643],
    [-19.849242404917497, 9.849242404917499],
    [-7.485569452227567, 0.5492713664931865]
];
console.log(  pointInPolygon(point, [ shape ])  );
console.log(  pointInPolygon(point, [ shape_in_reversed_order ])  );
```

Both return true, but should return false. Because, as you can see [here](https://www.matheretter.de/calc/geodrafter/?draw=polygon(-7.485569452227567%7C0.5492713664931865%20-19.849242404917497%7C9.849242404917499%20-16.369523519217765%7C3.8036530144735643)+point(-13.571067811865474%7C0.5710678118654782%20%22P%22)+&scale=20), the point is outside the polygon.

I'm not sure where this goes wrong, but if I add the starting point to the end of the array, it gives the right result. Is it mandatory for this algorithm to work to have the last point be the starting point (e.g. an explicitly closed path)?

**Comment by vHeemstra** [comment]
A possible solution/bugfix might be to check if each polygon has the same point at the end as what it starts with. And if not, copy and append the starting point for explicit closure of the polygon's path.

**Comment by osztenkurden** [comment]
Fix doesn't work for 
```javascript
const polygon = [[
    [1101.7962, 100.5449],
    [1443.0434, 120.2615],
    [1453.0800, -392.3705],
    [1121.8695 -382.5122],
]];
const point = [ -1940.6, -157.14 ];
```
Should be false, returns true

**Comment by rowanwins** [comment]
@vHeemstra sorry for the slow reply, I missed this notification. Yeah the algorithm assumes repeating the first and last point, I think I'll add a check and throw an error if the input data doesn't match that.

**Comment by rowanwins** [comment]
@osztenkurden I'm going to put this into a new ticket #12
