### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by rowanwins** [rowanwins/point-in-polygon-hao#12]
Bug copied from 
https://github.com/rowanwins/point-in-polygon-hao/issues/10#issuecomment-784516358

````
const polygon = [[
    [1101.7962, 100.5449],
    [1443.0434, 120.2615],
    [1453.0800, -392.3705],
    [1121.8695 -382.5122],
]];

const point = [ -1940.6, -157.14 ];

````
Returns true but should be false

**Comment by rowanwins** [comment]
@osztenkurden the problem is your last pair of coordinates are missing a comma.

````
    [1121.8695, <---- -382.5122]
````

**Comment by osztenkurden** [comment]
You are correct, late night programming does that to mind, thank you very much
