### ISSUE TITLE
FYI / use in project

### ISSUE THREAD

**Issue by theprojectsomething** [rowanwins/point-in-polygon-hao#16]
Hi there .. just a thanks and fyi that I've used your code in a recently published project [re:places](https://github.com/theprojectsomething/re.places) (a drop-in polyfill for Algolia Places), to help with geo polygon searches. The new library will be making it's way into [citizensgbr.org](https://citizensgbr.org) and [greatreefcensus.org](https://greatreefcensus.org) sometime soon. There's an acknowledgement linking to your repo on the [demo page](https://theprojectsomething.github.io/re.places/). Cheers!

**Comment by rowanwins** [comment]
Awesome - glad it could be of use @theprojectsomething , particularly for a good cause, that's what makes open source great!

From a fellow dive monkey (although slightly out of practice) :)
