### ISSUE TITLE
available in all CommonJS modules.

### ISSUE THREAD

**Issue by ghost** [rowanwins/point-in-polygon-hao#20]
/usr/src/app/node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs not supported.
logic-1  | Instead change the require of /usr/src/app/node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs to a dynamic import() which is available in all CommonJS modules.
logic-1  |     at Object.<anonymous> (/usr/src/app/node_modules/@turf/boolean-point-in-polygon/dist/cjs/index.cjs:2:26) {
logic-1  |   code: 'ERR_REQUIRE_ESM'

**Comment by GeraldGallet** [comment]
Hey @roeeovadia-pay 

I don't know how you are using this package, or specifically how you are using `@turf/boolean-point-in-polygon`, but this error made me realize I imported `@turf/turf`, which imported all `@turf` libraries, only to use 2 of them, none of which was `@turf/boolean-point-in-polygon`.

So to fix this, I removed `@turf/turf`, and imported `@turf/xxx` and `@turf/yyy` by name instead, which removed `@turf/boolean-point-in-polygon` of my dependencies, and allowed me to move on.

I didn't manage to force the `point-in-polygon-hao` dependency to resolve to the `1.1.0` version though, whch would have been a quicker solution.

Don't know if that will be of any use for you, but maybe if someone comes across this issue it might help.

**Comment by jwld** [comment]
Yea this release has busted my commonjs project via `geo-tz` 🥲

```
Error [ERR_REQUIRE_ESM]: require() of ES Module blah/node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs not supported.
Instead change the require of blah/node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (blah/node_modules/@turf/boolean-point-in-polygon/dist/cjs/index.cjs:2:26)
    at Object.<anonymous> (blah/node_modules/geo-tz/dist/find-1970.js:1:61)
```

**Comment by axel-michaud-cdware** [comment]
I manage to fix this issue by adding `"point-in-polygon-hao": "1.1.0"` as dependency. With that it work fine with the `@turf/turf` package.

**Comment by GeraldGallet** [comment]
@amichaud-ingtech I think we tried that but it didn't work 😅
Out of curiosity, what package manager are you using ?

**Comment by jwld** [comment]
Add this to your root `package.json`:
```
"resolutions": {
  "point-in-polygon-hao": "1.0.0"
}
```

**Comment by smallsaucepan** [comment]
Hi @rowanwins. Was able to fix this between turf and point-in-polygon-hao. Though the problem then shifts to between point-in-polygon-hao and robust-predicates, which doesn't offer a commonjs version. I'm not sure rollup is able to generate commonjs code to neatly import robust-predicates. Any thoughts?

**Comment by rowanwins** [comment]
Hi @smallsaucepan - I've pust republished with some tweaks to the package.json and rollup build process, so 🤞 v1.2.1 should work with commonjs

**Comment by patrickkfkan** [comment]
Has this been published to npm? I'm still seeing v1.2.0 and your `package.json` stays at this version despite the other changes.

**Comment by smallsaucepan** [comment]
Thanks for that @rowanwins. The publish might not have worked though.

Tried building locally with the latest changes. Unfortunately didn't resolve the issue.

Have gotten it working end to end locally, though it's a little bit roundabout. Send you a PR to take a look?

**Comment by rowanwins** [comment]
Doh my publish failed last night sorry - try again now

**Comment by hhanesand** [comment]
Hello, just FYI - we're still seeing this on the latest version. Using Node 22.11.


> Exception during run: Error [ERR_REQUIRE_ESM]: require() of ES Module <...>/common/temp/node_modules/.pnpm/point-in-polygon-hao@1.2.1/node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs.js from <...>/common/temp/node_modules/.pnpm/@ turf+boolean-point-in-polygon@7.1.0/node_modules/@turf/boolean-point-in-polygon/dist/cjs/index.cjs not supported.
> pointInPolygon.cjs.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
> Instead either rename pointInPolygon.cjs.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in <...>/common/temp/node_modules/.pnpm/point-in-polygon-hao@1.2.1/node_modules/point-in-polygon-hao/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

This is our dependency graph through geo-tz:
```
<....>
    └─┬ geo-tz 8.1.2
      └─┬ @turf/boolean-point-in-polygon 7.1.0
        └── point-in-polygon-hao 1.2.1
```

**Comment by smallsaucepan** [comment]
Thanks @rowanwins. That didn't help I'm afraid. Changed the error message slightly!

What I'm seeing ...

1. package.json defines point-in-polygon-hao as an ES module. So any .js file (including `dist/pointInPolygon.cjs.js`) is being interpreted as ESM. Renaming to `dist/pointInPolygon.cjs` and updating the entry point in package.json fixes this.
2. Once that is fixed running attw fails because both CJS and ESM are trying to use the same d.ts. Adding a duplicate d.cts file, along with telling loaders where to find it in package.json fixes that.
3. Once all that is done though the original problem will still exist, except now instead of being between turf and point-in-polygon-hao, it will be between point-in-polygon-hao and robust-predicates.

So you would still need to find a way to generate pointInPolygon.cjs in such a way that it can dynamically import() robust-predicates and still export pointInPolygon for use.

**Comment by rowanwins** [comment]
Have tried another set of tweaks for publishing as v1.2.2 based on the info in https://snyk.io/blog/building-npm-package-compatible-with-esm-and-cjs-2024/
🤞 🤞 🤞

**Comment by smallsaucepan** [comment]
Thanks mate. Point 1 seems to be resolved 👍 

Now looks like we're at Point 3:

```
var robustPredicates = require('robust-predicates');
                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module
  [blah]/node_modules/robust-predicates/index.js from
  [blah]/node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs
  not supported.

Instead change the require ... to a dynamic import() which is available
  in all CommonJS modules.
```

Point 2 is still moping around too, though probably more an issue for anyone developing rather than installing:

![Screenshot 2024-12-02 at 10 16 19 PM](https://github.com/user-attachments/assets/8369dfd2-a167-4164-8508-079c9db8d010)

**Comment by kiefer-olympiasoftware** [comment]
Still an issue for me when installing 1.2.2:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/robust-predicates/index.js from /node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs not supported.
```

**Comment by ghost** [comment]
> Add this to your root `package.json`:
> 
> ```
> "resolutions": {
>   "point-in-polygon-hao": "1.0.0"
> }
> ```

this still did not works for me :(

**Comment by ghost** [comment]
I am still getting this error:
please help
```
 Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/node_modules/point-in-polygon-hao/node_modules/robust-predicates/index.js from /usr/src/app/node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs not supported.
logic-1  | Instead change the require of index.js in /usr/src/app/node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs to a dynamic import() which is available in all CommonJS modules.
logic-1  |     at Object.<anonymous> (/usr/src/app/node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs:3:24) {
logic-1  |   code: 'ERR_REQUIRE_ESM'
logic-1  | }
```

**Comment by busma13** [comment]
> I am still getting this error:
> please help
> ` Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/node_modules/point-in-polygon-hao/node_modules/robust-predicates/index.js from /usr/src/app/node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs not supported. logic-1 | Instead change the require of index.js in /usr/src/app/node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs to a dynamic import() which is available in all CommonJS modules. logic-1 | at Object.<anonymous> (/usr/src/app/node_modules/point-in-polygon-hao/dist/pointInPolygon.cjs:3:24) { logic-1 | code: 'ERR_REQUIRE_ESM' logic-1 | }`

Did you try deleting your node_modules and installing again?

**Comment by ghost** [comment]
yes I did. 
I build a new docker with no cache and a fresh install

**Comment by busma13** [comment]
> yes I did.
> I build a new docker with no cache and a fresh install

Are you installing to yarn global in your docker image by any chance? In that case you will have to add the resolution to the yarn global package.json.

**Comment by ghost** [comment]
I am not sure what you mean. 
my docker file looks like this:
```

#FROM arm64v8/node:20
FROM node:20-alpine
ARG environment
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./
# COPY package-lock.json ./

# RUN npm cache clean --force
RUN rm -rf node_modules
# RUN rm package-lock.json
RUN npm install
# RUN npm ci  

ENV PORT 6000

# Bundle app source
COPY ./ ./

EXPOSE 6000
CMD [ "node", "./server.js"]
````

and my package.json file looks like this:

````



{
  "name": "site-logic",
  "version": "1.0.138",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "release": "standard-version --skip.commit",
    "start": "node --watch server.js",
    "publish": "node server.js",
    "prepare": "husky"
  },
  "license": "ISC",
  "resolutions": {
    "point-in-polygon-hao": "1.0.0"
  },
  "dependencies": {
    "@google-cloud/logging-bunyan": "^5.1.0",
    "@google-cloud/pubsub": "^4.4.0",
    "@google-cloud/storage": "^7.13.0",
    "@turf/turf": "^7.1.0",
    "axios": "^1.5.0",
    "body-parser": "^1.20.2",
    "bunyan": "^1.8.15",
    "cors": "^2.8.5",
    "dotenv": "^16.1.4",
    "express": "^4.18.2",
    "husky": "^9.0.11",
    "ioredis": "^5.4.1",
    "lodash": "^4.17.21",
    "mongoose": "^7.0.3",
    "mongoose-paginate": "^5.0.3",
    "morgan": "^1.10.0",
    "node-cron": "^3.0.3",
    "redis": "^4.7.0",
    "socket.io": "^4.7.5",
    "socket.io-client": "^4.7.5",
    "standard-version": "^9.5.0",
    "uuid": "^9.0.1"
  }
}
````

**Comment by busma13** [comment]
Oh, resolutions does not work with npm, only with yarn. There is a package called `npm-force-resolutions` that makes resolutions work with npm. I've never used it though.

**Comment by ghost** [comment]
thanks! it working now, I changed to yarn
