### ISSUE TITLE
Apex which is also lowest bound in y-axis is not in polygon

### ISSUE THREAD

**Issue by TomSwiedler** [rowanwins/point-in-polygon-hao#22]
import inside from "point-in-polygon-hao";

const polygon = [[[0, 0], [1, 1.41], [2, 0], [1, -1.41], [0, 0]]];

for (const point of polygon[0]){
  console.log (point, inside(point, polygon));
}
output:
[ 0, 0 ] 0
[ 1, 1.41 ] 0
[ 2, 0 ] 0
[ 1, -1.41 ] false
[ 0, 0 ] 0

**Comment by rowanwins** [comment]
Fixed via #25. Released as v1.2.4
