### ISSUE TITLE
False negative if the y-coordinate of the point is the same as the y-coordinate of one of the polygon's vertices

### ISSUE THREAD

**Issue by xThrodx** [rowanwins/point-in-polygon-hao#24]
The function seems to sometimes return `false` when it should return `true`.

I wrote a simple example to illustrate this behaviour.
The polygon has 4 vertices, and the point is inside the polygon but has the same y-coordinate as a vertex of the polygon, as shown on this figure:
![figure](https://github.com/user-attachments/assets/c4276f1b-5813-4062-9f62-30f93712df8e)

Here is the script:

```
import inside from 'point-in-polygon-hao'

var polygon = [[[0,0], [3,-1], [4,1], [1,2], [0,0]]];

var point = [2,0];
console.log(inside(point, polygon)); // Returns false but should return true

point = [1,1];
console.log(inside(point, polygon)); // Returns true

polygon = [[[-1,0], [0,-1], [1,0], [0,1], [-1,0]]];
point = [0,0];
console.log(inside(point, polygon)); // Returns false but should return true
```

**Comment by rowanwins** [comment]
Fixed via #25. Released as v1.2.4
