### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by XuPuPG** [rowanwins/point-in-polygon-hao#9]
for poly
0;0
4;0
4;4
0;4
test for points
0.0;3.0=true , but false
0.0;2.0=true , but false
0.0;1.0=true, but false

**Comment by rowanwins** [comment]
You probably need to close the polygon by repeating the first coordinates at the end. 

A fuller is snippet will enable me to help you better.

**Comment by XuPuPG** [comment]
yes, solve
